# App context configuration
server.port=8080

# In-Memory H2 Database connection settings
spring.datasource.url=jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
app.security.secret-key=3cfa76ef14937c1c0ea519f8fc472d9f4304207571dcb374a331dee76c49e7a7
# Hibernate configuration to automatically create tables
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable H2 web console panel accessible at http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

#AES Key (Encryption and Decryption)
# Make sure this matches your Angular code's SECRET_KEY exactly!
app.security.aes-encryption-key=k9X#mP2vF!8zA5qW@7bN4cC9xZ1vB3nL

