package com.authetication.project.utils;

import javax.crypto.Cipher;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.Arrays;
import java.util.Base64;

public class CryptoUtils {

    // Decrypts the default OpenSSL format generated by CryptoJS.AES.encrypt(text, stringKey)
    public static String decrypt(String encryptedText, String secretKey) throws Exception {
        byte[] cipherBytes = Base64.getDecoder().decode(encryptedText);
        
        byte[] salt = Arrays.copyOfRange(cipherBytes, 8, 16);
        byte[] actualCiphertext = Arrays.copyOfRange(cipherBytes, 16, cipherBytes.length);

        byte[][] keyAndIv = evpBytesToKey(secretKey.getBytes(StandardCharsets.UTF_8), salt);
        SecretKeySpec keySpec = new SecretKeySpec(keyAndIv[0], "AES");
        IvParameterSpec ivSpec = new IvParameterSpec(keyAndIv[1]);

        Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
        cipher.init(Cipher.DECRYPT_MODE, keySpec, ivSpec);
        
        byte[] decryptedBytes = cipher.doFinal(actualCiphertext);
        return new String(decryptedBytes, StandardCharsets.UTF_8);
    }

    // Encrypts text into OpenSSL format matching CryptoJS processing expectations
    public static String encrypt(String plainText, String secretKey) throws Exception {
        byte[] salt = new byte[8];
        new SecureRandom().nextBytes(salt);

        byte[][] keyAndIv = evpBytesToKey(secretKey.getBytes(StandardCharsets.UTF_8), salt);
        SecretKeySpec keySpec = new SecretKeySpec(keyAndIv[0], "AES");
        IvParameterSpec ivSpec = new IvParameterSpec(keyAndIv[1]);

        Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
        cipher.init(Cipher.ENCRYPT_MODE, keySpec, ivSpec);
        byte[] ciphertext = cipher.doFinal(plainText.getBytes(StandardCharsets.UTF_8));

        // Package target block: [ "Salted__" (8 bytes) + Salt (8 bytes) + Ciphertext ]
        byte[] prefix = "Salted__".getBytes(StandardCharsets.UTF_8);
        byte[] combined = new byte[prefix.length + salt.length + ciphertext.length];
        
        System.arraycopy(prefix, 0, combined, 0, prefix.length);
        System.arraycopy(salt, 0, combined, prefix.length, salt.length);
        System.arraycopy(ciphertext, 0, combined, prefix.length + salt.length, ciphertext.length);

        return Base64.getEncoder().encodeToString(combined);
    }

    private static byte[][] evpBytesToKey(byte[] password, byte[] salt) throws Exception {
        MessageDigest md = MessageDigest.getInstance("MD5");
        byte[] keyAndIv = new byte[48]; 
        byte[] mdKey = null;
        int count = 0;
        
        while (count < keyAndIv.length) {
            if (mdKey != null) md.update(mdKey);
            md.update(password);
            md.update(salt);
            mdKey = md.digest();
            md.reset();
            
            int len = Math.min(mdKey.length, keyAndIv.length - count);
            System.arraycopy(mdKey, 0, keyAndIv, count, len);
            count += len;
        }
        
        byte[] key = Arrays.copyOfRange(keyAndIv, 0, 32);
        byte[] iv = Arrays.copyOfRange(keyAndIv, 32, 48);
        return new byte[][]{key, iv};
    }
}
